name = "momsadl"
main = "src/index.ts"
compatibility_date = "2025-02-20"
account_id = "f846204052f664d57da7acde8f6803cd"

[vars]
# GROUP_CHAT_ID = "-100xxxxxxxxxx"  # Set via: wrangler secret put GROUP_CHAT_ID
# BOT_TOKEN is a secret — set via: wrangler secret put BOT_TOKEN

[[kv_namespaces]]
binding = "KV"
id = "cf5a4bd560504935a3efaface176b9d3"

[[d1_databases]]
binding = "DB"
database_name = "momsadl"
database_id = "e4dbebab-0287-44a2-8d48-368d1d992c5b"
